// <auto-generated />
using System;
using EntityFrameWorkCore.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameWorkCore.Data.Migrations
{
    [DbContext(typeof(FootballLeagueDBContext))]
    [Migration("20240428051049_SeededTeamsandCoaches")]
    partial class SeededTeamsandCoaches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("EntityFrameWorkCore.Domain.DataModel.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<short>("Act_Ind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Crtd_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crtd_User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Del_Ind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Lst_Crtd_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lst_Crtd_User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("coaches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88750200-9fcc-4c91-909d-969f1f421634"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8382),
                            Crtd_User = "rspihau",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8383),
                            Lst_Crtd_User = "dxqdlgi",
                            Name = "colmx"
                        },
                        new
                        {
                            Id = new Guid("7c558842-d686-43bb-8b81-a8c80b355fca"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8411),
                            Crtd_User = "hzzlddu",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8411),
                            Lst_Crtd_User = "kaemaeh",
                            Name = "fvrun"
                        },
                        new
                        {
                            Id = new Guid("08bc3731-263b-4b4a-a2ff-e68afeb57566"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8432),
                            Crtd_User = "dqzjbib",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8432),
                            Lst_Crtd_User = "enjoigu",
                            Name = "npkri"
                        },
                        new
                        {
                            Id = new Guid("1ffe8c20-eba2-48f4-b7e1-08e094182c1b"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8453),
                            Crtd_User = "lcfanjq",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8453),
                            Lst_Crtd_User = "xksrkyo",
                            Name = "ekapd"
                        },
                        new
                        {
                            Id = new Guid("0db84259-5269-459b-b3b1-62e790f0ac31"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8473),
                            Crtd_User = "nofwr q",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8474),
                            Lst_Crtd_User = "ytgdirb",
                            Name = "zaolh"
                        });
                });

            modelBuilder.Entity("EntityFrameWorkCore.Domain.DataModel.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<short>("Act_Ind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Crtd_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crtd_User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Del_Ind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Lst_Crtd_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lst_Crtd_User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("97612c26-55cf-466c-98b4-924b182195df"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8012),
                            Crtd_User = "hjgik z",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8019),
                            Lst_Crtd_User = "bs xgrg",
                            TeamName = "mbvablnz p"
                        },
                        new
                        {
                            Id = new Guid("22d8ec21-457e-473f-8a25-f3d13fcfa96a"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8118),
                            Crtd_User = "vkcwlce",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8118),
                            Lst_Crtd_User = "zlurtqn",
                            TeamName = "umrcpvtbzy"
                        },
                        new
                        {
                            Id = new Guid("36cb09e6-45a9-4ed9-87a3-a13f8cb82e94"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8141),
                            Crtd_User = "irkl oz",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8141),
                            Lst_Crtd_User = "ejlzldx",
                            TeamName = " efylbapra"
                        },
                        new
                        {
                            Id = new Guid("6a4deaed-9420-43d0-aeb1-ebe23c8cc236"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8162),
                            Crtd_User = "vavvpyn",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8163),
                            Lst_Crtd_User = "lwecodn",
                            TeamName = "lprbe nhzj"
                        },
                        new
                        {
                            Id = new Guid("ff667966-71e8-4e06-8c2c-6e723b76570e"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8184),
                            Crtd_User = "acwtvzi",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 4, 28, 5, 10, 49, 252, DateTimeKind.Unspecified).AddTicks(8184),
                            Lst_Crtd_User = "rcufifh",
                            TeamName = "gbghlftmzs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
