// <auto-generated />
using System;
using EntityFrameWorkCore.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameWorkCore.Data.Migrations
{
    [DbContext(typeof(FootballLeagueDBContext))]
    [Migration("20240501231129_TeamMembers")]
    partial class TeamMembers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("EntityFrameWorkCore.Domain.DataModel.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<short>("Act_Ind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Crtd_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crtd_User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Del_Ind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Lst_Crtd_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lst_Crtd_User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("coaches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da33e9d6-a770-4553-bb57-8f52cd603aa3"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1432),
                            Crtd_User = "wcqnjya",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1433),
                            Lst_Crtd_User = "ydsvdjr",
                            Name = "xzrz "
                        },
                        new
                        {
                            Id = new Guid("a14014e4-e253-4be3-82f9-8064b4d14aad"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1465),
                            Crtd_User = "yqwcwfc",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1465),
                            Lst_Crtd_User = "woxvmhk",
                            Name = "wtzqc"
                        },
                        new
                        {
                            Id = new Guid("d2787e2c-13e0-45e3-b9e0-521d37372d91"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1486),
                            Crtd_User = "qehmacr",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1487),
                            Lst_Crtd_User = "ohrsbbb",
                            Name = "trknz"
                        },
                        new
                        {
                            Id = new Guid("be4c9da2-29d3-43a7-8d3f-96d1e92ba560"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1508),
                            Crtd_User = "zeabdel",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1509),
                            Lst_Crtd_User = "yyqiuxt",
                            Name = "adalx"
                        },
                        new
                        {
                            Id = new Guid("05006a7f-711b-4f4c-bc72-ed86f13eb233"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1530),
                            Crtd_User = "vwuzufm",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1530),
                            Lst_Crtd_User = "scyyqzs",
                            Name = "jswt "
                        });
                });

            modelBuilder.Entity("EntityFrameWorkCore.Domain.DataModel.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<short>("Act_Ind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Crtd_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crtd_User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Del_Ind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Lst_Crtd_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lst_Crtd_User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamMembers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("355e1747-2ef3-40aa-a1a4-c5e94c167949"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(869),
                            Crtd_User = "vgjpwoo",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(880),
                            Lst_Crtd_User = "qzmxtuk",
                            TeamMembers = 10,
                            TeamName = "pbfvwzqxqv"
                        },
                        new
                        {
                            Id = new Guid("83565a8e-2832-4170-b7e1-053eb13ee77b"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1030),
                            Crtd_User = "xajinma",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1032),
                            Lst_Crtd_User = "fahizjg",
                            TeamMembers = 12,
                            TeamName = "fww pqxgff"
                        },
                        new
                        {
                            Id = new Guid("28dba2a0-ed24-4a2f-a731-30a7d072a525"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1074),
                            Crtd_User = "vhylp o",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1074),
                            Lst_Crtd_User = "ftlziuv",
                            TeamMembers = 9,
                            TeamName = "gjkjybidvc"
                        },
                        new
                        {
                            Id = new Guid("f90f4e52-5a1b-4d41-84f1-d5dfc660f90f"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1113),
                            Crtd_User = "awiyzm ",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1114),
                            Lst_Crtd_User = "kruerpd",
                            TeamMembers = 15,
                            TeamName = "yabmsktzhh"
                        },
                        new
                        {
                            Id = new Guid("75b0f6e6-855e-4832-be2a-f2c17e6fe0e3"),
                            Act_Ind = (short)1,
                            Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1136),
                            Crtd_User = "vgttnmj",
                            Del_Ind = (short)0,
                            Lst_Crtd_Date = new DateTime(2024, 5, 1, 23, 11, 25, 796, DateTimeKind.Unspecified).AddTicks(1137),
                            Lst_Crtd_User = "ujvgyff",
                            TeamMembers = 6,
                            TeamName = "xagccx mbj"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
